((:lexicon :relative "data/LEXICON-BROWN-AND-WSJ.txt")
 (:stems :relative "data/stem-dict.txt")
 (:stopwords :relative "data/stopwords.txt")
 (:concise-stopwords :relative "data/concise-stopwords.txt")
 (:lexical-rules :relative "data/LEXICALRULEFILE-BROWN.txt")
 (:contextual-rules :relative "data/CONTEXTUALRULEFILE-BROWN.txt")
 (:token-map :relative nil)
 (:external-token-map :relative nil)
 (:auto-init nil)
 (:report-status nil))
